import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    {/* biome-ignore lint/style/noUnusedTemplateLiteral: <explanation> */}
    <body className={`vsc-initialized bg-white transition-colors`} >
      {children} 
    </body>
  </html>
  );
}
